# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build

on:
  push:
    paths-ignore:
      - '*.md'

    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Bundle the Report
      if: failure()
      run: find. -type d -name 'reports' | zip -@ -r build-reports.zip

    - name: Upload the Report
      if: failure()
      uses: actions/upload-artifact@master
      with:
        name: error-report
        path: build-reports.zip

env:
  GRADLE_OPTS: -Dorg.gradle.parallel=false -Dkotlin.incremental=false -Dorg.gradle.jvmargs="-Xmx2g -Dfile.encoding=UTF-8"
